repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
        files: '^.*\.py$'
        args:
          - "--config"
          - "pyproject.toml"
          - "--fix"
          - "--exit-non-zero-on-fix"

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: '^.*\.py$'
        args:
          - "--config"
          - "pyproject.toml"
      - id: black-jupyter
        files: '^.*\.ipynb$'
        args:
          - "--config"
          - "pyproject.toml"


  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
