name: Do Github release

on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"
          cache: false
      - name: Build dist
        run: pdm build

      - name: Release
        id: github-release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            dist/giskard_vision-*.tar.gz
            dist/giskard_vision-*.whl

      - name: Push to Pipy
        run: pdm publish --no-build --username "${{ secrets.PIPY_USERNAME }}" --password "${{ secrets.PIPY_PASSWORD }}"

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: "C067920T38U"
          slack-message: "New release: ${{  github.ref_name }} is being made !:tada:\nRelease notes there: ${{  steps.github-release.outputs.url }}"
          # For posting a rich message using Block Kit
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
